apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin-secret
stringData:
  nextcloud-username: ENC[AES256_GCM,data:4KOJ9E4=,iv:LoWpX7r3UOFZA2s0I2GvLUXKvgZqI6E4mewhnt4/o8Q=,tag:GBEwmSCtqNcHJCHh++FE/Q==,type:str]
  nextcloud-password: ENC[AES256_GCM,data:DYPCqUE=,iv:q4TvpXbvpcC0Vk5cgxuxZ4RhbEN1XfHlxAUqNM6tfrg=,tag:gU6BEudk7tRZd/L23p3dIg==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbXQ2a2J1dXNVcWYzWjRp
        OGVGSWZVZVFRQWV5WnAzWHRLS0w2dXFQWHo0CmN3SVBZYzFFK3NzeG90N25PUi82
        UDV5T2ZVV0YwY2d4anQxci9mU2NMbkUKLS0tIHVkQjF6bnFyVGFCV2RjQU95UFRT
        VHNnS05CcnZKZFZEbVdiWi81cnVvSkEKiqrLCE9J976B0L1I75JPF3Z2eX3q6ffF
        eT9hahEo3U3EUB+6BnKkpaNmE5IUC/UljamlFt8UIR9dEfmyFJwXdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T19:56:56Z"
  mac: ENC[AES256_GCM,data:XUWPJj40Dxg55SOV/ZjgPD1XJ2GbPAJ67pilr1k1udZje6xAxk5o6evjd2/KUAOuo1G2EWT9v79PdKqY+GsbSwOMm13c/2AzW5typeZbBYTkIVeNW0Uhf2IlsVXsc5BOX6hI48BuDG0Ozjhq8iVup586NSQUBk9Ap7kCiMpexLU=,iv:NfUzWaa9ew8cpz2fTJ+BV0YH/Er7BILgzjJrM93GWYo=,tag:N43bxnXXL8yNgVRd7Qpjzg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
