apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:TAgi+WujGSeOWce0mmuaNz2DmSBGKtxItUkRNLk9OaqyS1W114tbNcqGebXQwx0AWobTARE=,iv:BFijxXTcr60Q7D26etagR44+6PRX40F2O2fx2Eef61M=,tag:GmO6YF2Cm79AbzK2lfUf1A==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTVMxRUNUTmdVU2lRRFBD
        UlpUenZKZ05TSVhHeWpOdDYrblZ5L3RRT1ZBCi9LbUJUVURPK21Xa3VFWjZlVkFR
        b0dYcmhRMHVsdlhkTnBMOS9DTVZ6WkUKLS0tIFg2eU1UZTFncjdobVdMb09MVTYr
        cDk0N3VmckRxeWxqZDI0M2g2ZWY5dVEKk/FMEMVHZ8/+zgSFduM3s439LVlwqHII
        VL6fKdTKmXp4fCHV5Ym/2n+ZZn9Hk0TiUv+45Xpk4xNIC/X4tJEifw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T01:38:27Z"
  mac: ENC[AES256_GCM,data:cGZ61H2M3erBNmBE+/TEOWmoKaoBvcZJwZsc+bG+McniEHf74Rsl8F2jzh9UJSvRCs8O93rbXDeTyR1N0X74+MaVa0SL2p6y7g3Bl7VXVrCY34d7siPQRut/Y7pYL06jI9oRbyNoWVEzLgX5D5jL/j5XXlg0joPcwdJ68C24ac0=,iv:4bgSgVfNrbyx3Ry4RgRzMzBYaXu5F2s0L118AkIAY9g=,tag:rc/Iadwh9cvJs9lVZBB9lQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
