apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:fwTuBU9WHH9UqjViuA==,iv:GyHf1fVQlH+g35gFUwPlARmWiRvdMjNVaeFg/pnkfXw=,tag:Q0co5YxQhAbTlqSiO+7kuQ==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWmJCZDlFQzZYYjAyL29J
        blFiQ3FrZ3R5cXg2RTJ2QkxNOTFOM1JudlNzClFMMk5RYW9Wa3lJNk9jVkVEcjJo
        akxTQjg3cGlyeTMvRm8vQ0NaYkN2aEkKLS0tIEx3Q3ltaGF4QmxXd0l0WDRvcTd0
        cmN4RUE5SUdTM3FrTWoxT2I3SG9mQnMKN+HWdhZ8DH6GojQ3YTSor/CWpGjxEvsh
        B1j3G2AWWo1MTW3LAPELYbmE5P10Y9GWUJczHKHl6BdhVNU5sOkIuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T01:38:27Z"
  mac: ENC[AES256_GCM,data:ZjCkimvlOqG1FWcV8OEHgUq3NyTqxOs1Esk4bOn+vSQt9BlQkqtpBQ34l0FgKRrfPtCOqXapnI3jcJDjQiEHGy59/XxRHWb9fZHkb50UR+Tj7A1UcInzNoWWYw3ZkDg69u7Mzdes/pq3Fo+p7euDoaZ2z8/l+jLU3cSp7AaaLSc=,iv:1ZSJcfRESs92QfGcmaT97k/0R4gBq6FDE4VEYuOxsBw=,tag:nctB/Id6jXx+zR+TC8ozIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
