apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:fGBrFA5ej4BlbPt2rtGgcWHFalxOcpvOB6LbJQBa8qM=,iv:CMn1cpOB3wAhhz0oKLiNRIdrczNEYpMsPVTlsjPYzfo=,tag:heTXa4kbOLSc1rD8zSToWA==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMGpGS1FlODVweUMva0VH
        Z2dSYnBRS1EwWjl2Zzg3em5XeWpqNTNzeVVzCmdMaXVNMW51UVdiU2xiWjZ0UnRY
        ZUFNZmhWMHJPeWVWRDdoNDFXelNibncKLS0tIGJza0NDb2NBN3NvWDRZOEpuY045
        Wi90bi9DZTRRaUwydkMxSGNSOXNpeVEKOCxfkG6JBH0qT22TDrRDHEChWEKtr8Sd
        IMHeNE5HTRzXuZHWD+5ronotVg0XFc/QVVmyV5QIlI6rbqnchl7EPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T01:38:27Z"
  mac: ENC[AES256_GCM,data:eKQjAmwQ1WhyH+BTzaYzGuvZmMRXawuU1P1Ky+bW6BCmojm8okwpdc4XuYiz3kx2IBXdZCUC7ZHkKieSFUXHrT+/iM7QgUN3wsFXqkO8Xj4HwaMIaOhH8L/wmE7P8muRn6km2ez6V2hkSLQ1mTJQcfjy+oz4qQypSlXOlEcm0+A=,iv:4u5a8MFAde8Bujyet5KaiqRxStbnHe0HCcnbjJyj3Qo=,tag:O5hnOUdFy1pNL0xWvHIBnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
