apiVersion: v1
kind: Secret
metadata:
  name: paperless-admin-secret
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:lDKagnE=,iv:pAQ/7vxRQMfhDHKdvYN9T1pGDpCciBMmI4NwrE5gwbE=,tag:YimwLm5VC3umnV3iLggvvQ==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:MY7kZGHKDgYnEsfTjcZwDzkJEj2cVPuKhBA=,iv:bPX4JWYeBTQ8/1eLu0+p7jhd8gwP1/ofFI7MdZEIYoM=,tag:1j57GUphXm4LzkMQvqc7TA==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZEFYTVhJR2hxb1RJN0Q4
        ZDZRcTZOa2FZYmJYOCtMNFJEYVd0cEIzRUUwCkpHS0NubjRUWkFvTzB5R2ZjcUZR
        NHlXZzJrRUdqN3BsbXRWM1FTOXZYUUkKLS0tIFJkUlFVdkJXMnpONlA1V0NNMnRJ
        Z3F1akRZcjhEYXFsRlNDa1JPK21ZSHMKPCFGjXuvz8XHRA1IdSYK8YABghddidm7
        RWsVdlQKdrwIkVd78nbAJK663+c8R5hkZBBMV9cyI/iaHtON/PXJYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T18:08:16Z"
  mac: ENC[AES256_GCM,data:zVqEluIKZFlGZnaqiz3GKaz86q6U5Zn0L1OGQW4ltXC6slN8shSg87lJ/Cgns4o2WiVxenxOgelEX1SxfL55AXUnmKqw1xoGZ1Idi5U6igJIa5xZT5B+UkkbVuQXEEeiaOyeqfj42IomLj7lTrDWctuxkENg6jAs/9x+fncQ22E=,iv:bJpIncnUW453lt9MJ6lxZNx47JFxU1EI/zlKHaR7M5I=,tag:god0NyaX2vMbTH9BJURZSw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
