apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KxldmZicnDMlogj1cJWsn/JC2XX+6B9rYV286ftO/htRurmzcMrttqXEtijpiLADxjbeYoJn2DxZ23iGNOn0rMZP5DGudki+oGogx59MwdOwd8jurNg6Vs5CIC5L4WlkNReMVPGV5e6EOj19N5RNgB43aRirr+q0ObLmkwVar9hetRYeAm8UU2/4Co1LXt77EH0vWlcNrEf4mPaabpI0Ibw9IgoJQKOw+7ZetNfwCDdwngQG,iv:E81M9JrSuVKnqYFsjpryHm7NQgdzw3qpR1uIVjjJsAI=,tag:y0YfMqmZtf9FZjgSp4OovA==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdTNPa3RTY2dpWGh3SWU4
        SEFoVWJsbVFuS2J0SCtpcWFuZXVqNkU0bndBCmc2bndVQ1RndE9ubEJDRVBvUlFH
        OVc5VW95S0NHUGsxU1VlSHZ6TWVxRmsKLS0tIG5KNUZybS9MdGJNWW9FT0V6Ni9q
        RmxLTWsvcHJTUExLSHBucmtuZVhuWk0KUK2EK5AY+3zXe2jGYGQE5OiUTiMwDxBQ
        AxXqsdiLSqyvlY0ZhEXlK3LljyOGp71ITrq9+3MPekPFhh3oI5xQbA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T01:38:27Z"
  mac: ENC[AES256_GCM,data:9OahD2gCiSGRtCWtvKVmmiqyPsBgyj6SR9Q4dvh0vNv7KbwJITbMLUlPFkht0yIWGTic2XvWEdExpy4pgTy24fCTrM5ZvZDCtQCPPoJHUMiJKz1KhLMluyc6p1CYBcg22xthYU7G1m9liU3JUUqBSDGjUWH/7bYoCsKPRzCbT5U=,iv:T/bMi2vcez/I/d1n2qZsrjsR5BphyW9hm/Lqg/qmPqE=,tag:B7STD34X2iDyUAGwkoKXkg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
