apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:r0yc5H3emRUu0ydMFAuroOr2iwImKz7LgXvKMhePcu5AvBde4/gSpjE1XwzOUZc5/E+NA4I=,iv:hgZ2BfU1DU+nExAvJzf77ZehcI010ZisBqdE1iOoEj0=,tag:N4EIhT+Ea13LnQICP9MNVg==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU05HMldEN0dFNUhlM0k2
        TVp1OC9HYm1JZ3IwSmZxdWZKakEyUmRVanlJCkxTRE5nVmF3bGpoK0RKV0tkZm5i
        RXBRcjRVV29mMU54UnBpTTNNcWdXbjAKLS0tICttUjc1OWpkUDlrYnR6bmxKWHN0
        NkZ5WE4weU5QUlZ0bzRuSG9RaCtaNUUK356QomG/6nc2rmp6c2Z4ti80rQ2utdgr
        8cVEjXrs47fY10GIgQ3FVp/8AyTAaFpIHSDuvwtQRp2/kQK0eCNUHw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T01:38:27Z"
  mac: ENC[AES256_GCM,data:PGmJipORooW2kLvoLw8MA1ofiMz6smPBEDD43NegsXTDkjAY2Y7w5Q4IGGCvO4GUNI2A8CnKvomNwkcM8be3vyXMelJ1SdBUYXG/26N0dvvuGoLMRDHZ1+YOtv9Ugs6ZFnvPAwo5GVPeM3XW82gx+0TcRjgWcpSwJLyCwHMlTlI=,iv:e4N7uQDRD3BfJ+yGEE4IMPWSwm0J1G+YuCKCYhe5XWw=,tag:BYC8uajivTTMu5EcpHi/NA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
