apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "schloschi-com-production"
spec:
  dnsNames:
    - "schloschi.com"
    - "*.schloschi.com"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: "schloschi-com-production-tls"
  usages:
    - digital signature
