apiVersion: v1
kind: Secret
metadata:
  name: paperless-admin-secret
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:+qzywD0=,iv:829f8IxH4iPV6L+dFxJz01sqnoQGvnDzZSXfQhmrbnY=,tag:ar+6dGeDjmBbXrhkjPARBw==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:oeUdLC/swe2dhSi6eyoiNPZnokTIvUVVSTs=,iv:3wgzMsxnvIEGbi68hikOWL6dTB2V2d90kyzyUcBLjfQ=,tag:V9u5cN4K6gTeJBOnClirtQ==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWXFma1ZSV1U1YS9xV2V3
        UitQcFFtYlFpRFhyVDdpaWwxc1BlWTVZaW1NCjJicmtreW9wK0J2R3VQNm4xZmxM
        dVprWFdsWUkwUXRPWi81MzVXenk1V00KLS0tIGh1SjhxWDhoUmp3blY4aUZuNTRl
        THp0U201eDdGZjVnWTZhc1pHYS9wVUUKZZcBdpBgAkcXYjqVgOIJqXUNXyrFy2sI
        0+J/0VMngs6QccWQo/akQokaWRmZlTvqvgxv9lmpc3ba60p2u3IkXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T18:34:09Z"
  mac: ENC[AES256_GCM,data:OOKfzmJSAFsNzFiBqmP9VhzGro4L33dleYW2q/Y8M89BTwsow73rcuBBXo2LAT7wMIZ27DPtTClowU1Z+K2Jnn/+pK1pH3mSrWC+TYvELogf3DpTf1+h2SiWnyQHXmwnuBn4TDYrrkoMXSXn+yRM6EaQO/0YIqbCLEZRlCGDVSo=,iv:+RctSzhGsX4c/kOqO1ohmFc9gaNyUY021J+lGtbtyJ4=,tag:65fQ8YgO9Mfau+jxoKZtoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
