apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-postgres
  namespace: default
spec:
  serviceName: immich-postgresql
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      containers:
        - name: postgres
          image: tensorchord/pgvecto-rs:pg14-v0.2.0
          env:
            - name: POSTGRES_USER
              value: "immich"
            - name: POSTGRES_PASSWORD
              value: "immich-secret"
            - name: POSTGRES_DB
              value: "immich"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: immich-postgresql
  namespace: default
spec:
  selector:
    app: immich-postgres
  ports:
    - port: 5432
