# kubernetes/apps/default/immich/app/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single # Point to the new StorageClass
  resources:
    requests:
      storage: 900Gi
