apiVersion: v1
kind: Secret
metadata:
  name: immich-db-secret
  namespace: default
stringData:
  #ENC[AES256_GCM,data:KuHKDCmBzhKWkMjq9AQTkP/r3iSh2i3mw/fB,iv:bhmhwFsHW70OPzushLEsYQvvjpuCOHXNrHfsE05IXFo=,tag:BzgB3AzJi5zVKxtzjGy9MA==,type:comment]
  DB_PASSWORD: ENC[AES256_GCM,data:HrE3thgCKH4hcLgGaWJC27qE4/nooHGpHOI=,iv:RiiKgUmoiMqSEA/uI0yZKAxEwU2hFCKyisD2RuhwTqE=,tag:+tsp1dJoAOTj4dw0VcZgHQ==,type:str]
  #ENC[AES256_GCM,data:2ZTNmv5VQJogj6GKtzy82WSm1/1t5iE5DpYSP0k=,iv:UwpLsUoVShNKYp5pdA7/3mQzp5n4PMf0bUo158PG56s=,tag:6AOh5PurE5w0s8IMOz3AOQ==,type:comment]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:Zm8dlwgm+nDhscTWbZu4LJgcCgOU4zaSFGo=,iv:eSLnCWbT40Czn+dc2LclnT/NQ8NmoEZTedqt3ox01gI=,tag:wXVbO1LnCWAUIxD51TBU1g==,type:str]
sops:
  age:
    - recipient: age1qf20kjavtc0v9eeny8s2qg43r0rk7xcw9fjvyc96daax4nvrudaqts4qdr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNlRiYVdocVJuNkpKV0VT
        RGV6MGYxcTZabW9Ra29nQk96RG5VZis4YUZVClQvNUNVU2FnTjJrcnI0TEdhSC9W
        MmNDZzh6UlBjcmg3elh6MUVudGZvN2MKLS0tIHBsR0VtaklRVzkwMnFGNjlzWG11
        Mmdtd21Da2FJYzg2a2xHaGxaWVBJdk0KCNn3vwnEL2f+505o5+ciht1vPYHUXo7W
        CUCWtm9PkiU0sLcVKJH6xZcq/6DlAg+yon2W50vy6tMO5DRi8IgcQA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T20:06:53Z"
  mac: ENC[AES256_GCM,data:6iEqOUxQxMbngp6haJYzr77oHBmuMf8YOFy5uNZY4YjSRjw+OXAL6l7Ugg8PCNeNBuS5NuVRSvJrsMXkSyl6jyx7BcMUepeEZAXekKvLLlLmdqbfYYX7G9mcSwKUef+F07DxgzZCYaEi26r9eNWnUnRS0jndos6l2js929JAPwU=,iv:iMKSNDbUiRx2GiUswBsBEYL4CoHsUcWJx5YL2Tjz+Uo=,tag:mAYfKOPNzCBsqMUzvrWJuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
